# Generated by Django 5.2.5 on 2025-09-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_id", models.CharField(max_length=120)),
                ("name", models.TextField()),
                ("ingredients", models.TextField()),
                ("cooking_time", models.IntegerField()),
                ("difficulty", models.CharField(max_length=20)),
            ],
        ),
    ]
