# Generated by Django 5.2.5 on 2025-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="no_picture.jpeg", upload_to="recipes"),
        ),
    ]
