# Generated by Django 5.2.5 on 2025-09-05 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="recipe_id",
        ),
    ]
