# Generated by Django 5.2.5 on 2025-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_recipe_recipe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                max_length=20,
            ),
        ),
    ]
